name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages Docker registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push backend Docker image
        run: |
          docker build -t ghcr.io/gadagojushiva/fullstack_student_management_application/backend:latest ./backend
          docker push ghcr.io/gadagojushiva/fullstack_student_management_application/backend:latest
          docker build -t ghcr.io/gadagojushiva/fullstack_student_management_application/backend:${{ github.sha }} ./backend
          docker push ghcr.io/gadagojushiva/fullstack_student_management_application/backend:${{ github.sha }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t ghcr.io/gadagojushiva/fullstack_student_management_application/frontend:latest ./frontend
          docker push ghcr.io/gadagojushiva/fullstack_student_management_application/frontend:latest
          docker build -t ghcr.io/gadagojushiva/fullstack_student_management_application/frontend:${{ github.sha }} ./frontend
          docker push ghcr.io/gadagojushiva/fullstack_student_management_application/frontend:${{ github.sha }}
